[package]
name = "resolv-conf"
description = """
    The resolv.conf file parser
"""
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["dns", "unix", "conf", "resolv"]
categories = ["parser-implementations"]
homepage = "http://github.com/tailhook/resolv-conf"
documentation = "https://docs.rs/resolv-conf/"
version = "0.6.2"
authors = ["paul@colomiets.name"]

[dependencies]
quick-error = "1.0.0"
hostname = { version = "0.1.5", optional = true }

[features]
system = ["hostname"]
no-strict = []

[lib]
name = "resolv_conf"
path = "src/lib.rs"

